package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock" //nolint:depguard
)

// MockCommand is an autogenerated mock type for the Command type.
type MockCommand struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, name, args, dir, env.
func (_m *MockCommand) Run(ctx context.Context, name string, args Args, dir string, env Env) error {
	ret := _m.Called(ctx, name, args, dir, env)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, Args, string, Env) error); ok {
		r0 = rf(ctx, name, args, dir, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunWithGracefulShutdown provides a mock function with given fields: ctx, name, args, dir, env.
func (_m *MockCommand) RunWithGracefulShutdown(ctx context.Context, name string, args Args, dir string, env Env) error {
	ret := _m.Called(ctx, name, args, dir, env)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, Args, string, Env) error); ok {
		r0 = rf(ctx, name, args, dir, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
