# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [01_init]
  pull_request:
    branches: [01_init]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GO111MODULE: "on"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
          working-directory: ${{ env.BRANCH }} 
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: branch name 
        run: echo "env.BRANCH=" >> ${{ env.BRANCH }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v ./...
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ${{ env.BRANCH }}

      - name: make build
        run: make build
        working-directory: ${{ env.BRANCH }}

      - name: make test
        run: make test
        working-directory: ${{ env.BRANCH }}  
